### ISSUE TITLE
fab local_bootstrap error

### ISSUE THREAD

**Issue by mazhang2718** [nprapps/playgrounds2#843]
Running `fab local_bootstrap` gives this error:

```
Fatal error: The command 'local_bootstrap' failed because the following required environment variable was not defined:
    settings

This variable is used for specifying which server to clone the database from. (Usually "staging".)

Try running one of the following commands prior to this one, to fix the problem:
    production
    staging

Aborting.
```

And running `fab production local_bootstrap` or `fab staging local_bootstrap` seems to require an ubuntu password:
```
[54.214.20.225] Executing task 'local_bootstrap'
Cloning database from production...
[54.214.20.225] Login password for 'ubuntu':
Stopped.
```

We're pretty sure this is just an issue with ssh keys not being on the server, though it could be something else.

**Comment by eads** [comment]
Sounds like ssh keys not on the server to me. It should always specify the dev target.

**Comment by ghing** [comment]
Yeah, that's the problem. I asked Matt to make an issue so I could follow up on it while I was slammed on other stuff today.

**Comment by ghing** [comment]
Matt said he ran `fab update_copy` and this worked ok, so we run into problems with the `_download_data()` fab task.

**Comment by ghing** [comment]
We added @mazhang2718's SSH public key to the `public` and `public-staging` EC2 instances and he was able to successfully run `fab production|staging local_bootstrap`.
